apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: astronomy-shop
data:
  ENVIRONMENT: dev
  CART_SERVICE_ADDR: cart:8080
  CHECKOUT_SERVICE_ADDR: checkout:8080
  PRODUCT_CATALOG_SERVICE_ADDR: product-catalog:8080
  PAYMENT_SERVICE_ADDR: payment:8080
  RECOMMENDATION_SERVICE_ADDR: recommendation:8080
