apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation-config
  labels:
    app.kubernetes.io/name: recommendation
    app.kubernetes.io/part-of: astronomy-shop
data:
  ENVIRONMENT: dev
  PRODUCT_CATALOG_SERVICE_ADDR: product-catalog:8080
