apiVersion: v1
kind: ServiceAccount
metadata:
  name: recommendation
  labels:
    app.kubernetes.io/name: recommendation
    app.kubernetes.io/part-of: astronomy-shop
automountServiceAccountToken: false
