service:
  name: recommendation
  environment: dev

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/recommendation"
  tag: "7bba83fe981eec0176592a4831111f7bd5700350"
  digest: "sha256:2daef45dbab5138f9de71e249010f583f597484208d17537ae902f4983b4db36"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: rollingUpdate
  maxUnavailable: 0
  maxSurge: 1

observability:
  metrics:
    enabled: true
  tracing:
    enabled: true
