apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    app.kubernetes.io/name: cart
    app.kubernetes.io/part-of: astronomy-shop
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cart
  ports:
    - name: http
      port: 8080
      targetPort: http
