apiVersion: v1
kind: ConfigMap
metadata:
  name: image-provider-config
  labels:
    app.kubernetes.io/name: image-provider
    app.kubernetes.io/part-of: astronomy-shop
data:
  ENVIRONMENT: dev
  IMAGE_PROVIDER_PORT: "8081"
  OTEL_COLLECTOR_HOST: "otel-collector"
  OTEL_COLLECTOR_PORT_GRPC: "4317"
