apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-config
  labels:
    app.kubernetes.io/name: checkout
    app.kubernetes.io/part-of: astronomy-shop
data:
  ENVIRONMENT: dev
  CART_SERVICE_ADDR: cart:8080
  PRODUCT_CATALOG_SERVICE_ADDR: product-catalog:8080
  PAYMENT_SERVICE_ADDR: payment:8080
