apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: checkout
  labels:
    app.kubernetes.io/name: checkout
    app.kubernetes.io/part-of: astronomy-shop
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: checkout
