apiVersion: v1
kind: ConfigMap
metadata:
  name: currency-config
  labels:
    app.kubernetes.io/name: currency
    app.kubernetes.io/part-of: astronomy-shop
data:
  ENVIRONMENT: dev
  CURRENCY_PORT: "7001"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
