apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: currency
  labels:
    app.kubernetes.io/name: currency
    app.kubernetes.io/part-of: astronomy-shop
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: currency
