service:
  name: checkout
  environment: dev

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/checkout"
  tag: "586773936c2c08ec4bcaa728df37718a655e2e9c"
  digest: "sha256:0c7cc193492fa9ac21e1f4e17f06c5925fb66156c110ff5909de29334a74e21a"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: rollingUpdate
  maxUnavailable: 0
  maxSurge: 1

observability:
  metrics:
    enabled: true
  tracing:
    enabled: true
