service:
  name: recommendation
  environment: dev

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/recommendation"
  tag: "4e561eff42935bd413e25ec8ef3095d321b773a6"
  digest: "sha256:c337a053265e508048a7c92fe354239defeb12c16332a0e0451adc08f033a72a"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: rollingUpdate
  maxUnavailable: 0
  maxSurge: 1

observability:
  metrics:
    enabled: true
  tracing:
    enabled: true
