apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-proxy
  labels:
    app.kubernetes.io/name: frontend-proxy
    app.kubernetes.io/part-of: astronomy-shop
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend-proxy
