service:
  name: frontend
  environment: dev

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/frontend"
  tag: "f1263d4072f8129fe204873c9b7f654ad5258445"
  digest: "sha256:a511413241e60db625339e18effe0cbb64e584fc1b5f5d133fb485cc2b2e4ff9"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 150m
    memory: 128Mi
  limits:
    cpu: 400m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: rollingUpdate
  maxUnavailable: 0
  maxSurge: 1

observability:
  metrics:
    enabled: true
  tracing:
    enabled: true

httpRoute:
  enabled: false
