apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: recommendation
  labels:
    app.kubernetes.io/name: recommendation
    app.kubernetes.io/part-of: astronomy-shop
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: recommendation
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
